sudo: required

language: go

go:  
 - tip # The latest version of Go.

services:
  - docker

env:
  global:
    - secure: "Zr8bYx7WOyX6/QqwPHCc/x+NEtgmWxN4PpdKD0OL8V/MJhLX5dgZ5g/uun3bm41+0vNjLGktSC3xY/E5giPuWCcmQn3sazjRWkrq0LQxu/vTDq/6msMLMwmfZ3PXMvqCmc6j6h9h6UQtfpd2qLXJWW77GTUeAt1zlnB5av/2jIKQLdrhAVr5pKBN9SOc3M3MtfK3VwgHaJrfAuua99PW7xl0RnJtSmesIST1XgeX04sZe/j339xti7OnTodthnaYsYaOkTeETv4jNITS/NcTUAlHhLDARQYLBy9LlkmYoWc9QguZdtkTLkfWIacue4CrwLmo9fG96aC9AYFokF9PqCZRkJCzs8UcjcZZ6S/5vD4/SWuOSxBwx7X2iIH2w4C6OOzl013HFdWDSRS8FghCZ5MzkDY1f/Zhkfod66wF7V4qyPiYJxcSZGO3MTH1gO110dLWNtqKZRMsLGp80EK3zUZ67YUemHGk8NwZWjKaSTUurqflrv8X6wJ1/cE5RXW/DsdbOx1m2ombtI7l80DbsOSZSJXBZ+ualwSxd3jmfBBPWt1o4UZnp/3DTjAuvIImKiXbQBOtO9vf2avWwjQew9r3y/A1/OnIseaRVxpSY+a9D8sqwL3l+N7WgpZmTcipVFFgnhQgodKFGHqU/JbeWnpqHmWeUDKyCbaKPsPIjYM=" # DOCKER_EMAIL
    - secure: "qaOE9aisTkDv2/5WYtJqIcOaY2jl7XnvWyrrKhVdbzZDSDCg21TKTqLXynd8HPM9qn2IhyKp0NnM8fErGRPxX2/XTp5mDHUYRaCGM3QGTOOoFl2uHtBHIcHu8mYTkv8VVgwQzc0h1Sj8dAedaV2pqpiOiCMKh5f4g258n3iycoLugU1Mj1uzqglJGU/OgI4/WARDR/0PiqOOzKJhElmM5kVAlCVnWUZNTOvFWdwlAixRe1Gzub7AUZ1I1W1iaFo9YtANaIqc1YEv8m/wII04jX5duAIrPiWa5Ln82+0gtAmELtfpvJOeG+IgL3sgOqKQ/t95OC6a1QFpvifUY104wsZPute12tBasVrDcoTH4Tu3/SP48XmDfnLcryuryrbKSwHc9vJSq8hP37mOud5F2Ui+TEIfrPFnzIgOJzNMyhGB5H7yn3d46aYcIe+C96VHo3lkaZQ54XzlsI1mS4uL6LxAuSmBkceux9CzIuD+hUx5hTAwJYO77lGRpQb0UJo1GJApkxb/X5Wo75URIdk+AGJc9lERG7WlX+H0aC4kWHjoJr4GM7dbZHkq5TcI+TkWC/y4Vlz6Nb4IjGE7cwhWf2fKiFgXDPCBWpZoV6lzKW2Ktzs90dInVU4jS7Xp46kTBA9OAiHZziXpMRuILMHy+hCBLcaSp0U9AR4QCyXp3O0=" # DOCKER_USER
    - secure: "dBakWHPC8Yf39zsPx3JdlrlV9NQuY962U9DuD3DsonK/cFlXmUX18K7+0rwJK3J/4I0BW8DVjmFg7gi5pIsPyIjD0J26t+A010TJE88HvCgmnJWkIuQ73FlNZZrL7QnqPWRarn8bFMMUKDF0aqCu/1ltUalbURPmU3EA3QEmMeFdRD20o4Cuv0/t7mlzD4Z4V2EBCn5jxy873mc2gy9LbMfn7u9zPf0tFpjLhXz4KiFE2Z7WaPvUbTuq14si3/ylE7cTa3vm2Bhxl8+A0hwjTzZlnvEyPcbUeeJTA7MkEYBC3F8kcyZ72iYnI5SnmflRLJHsP8O0vAv38yIQeJeSvnENr2C9Sw38pUAieSJ7ysQCkJnjECr4fyOoLI21ZMq5VIaxUvS04Kfh10kQmp0pH+ASw5Gu5lG4X9y6+JTzVW648saC07FJ1JKzglKqqs4Y4C9QFQFWtGyTF1r74sk0rZlxFQvSTmS3a9C0NNu5+q238nHenWxqngjRcF+IhFkQLfMGGN1+MM1boFXDR2uMZcOLo3N8gsOzj0dO1HIO5nJ+lL96Qj3X7EgaV7fwgBGhcd8X7pqP5Uwa52gfr/McFVOvTvopSjkDi4JePtuy+fMQ5dLT6r43UMeiGFwGAA0U8lYhJNBNGGTWZy0zIfq41MxC81j0cCwKDWhtJaB6dlg=" # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::8}
    - APP_DB_HOST: "0.0.0.0"
    - APP_DB_PORT: "8086"
    - APP_DB_NAME: "homedatakeeper"

before_install:
- docker pull influxdb
- docker run --name -d influxdb-test -p 8086:8086 influxdb:latest
- docker ps -a

script:
 - curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE homedatakeeper"
 - go build
 - go test -v ./...

after_success:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=dlaize/homedatakeeper
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO