
version: "2"

services:
    
    influxdb:
        image: dlaize/influxdb-rpi
        restart: always
        container_name: influxdb
        volumes:
            - ./influxdb/var/lib:/var/lib/influxdb
        ports:
            - 8086:8086

    homedatakeeper:
        image: dlaize/homedatakeeper
        restart: always
        container_name: homedatakeeper
        depends_on:
            - influxdb
        links:
            - influxdb
        ports:
            - 8000:8000
        environment:
            - APP_DB_HOST=influxdb
            - APP_DB_PORT=8086
            - APP_DB_NAME=homedatakeeper
