
version: "2"

services:
    
    influxdb:
        image: dlaize/influxdb-rpi
        restart: always
        container_name: influxdb
        volumes:
            - ./influxdb/var/lib:/var/lib/influxdb
        ports:
            - 8086:8086

    statusok:
        image: dlaize/statusok
        restart: always
        container_name: statusok
        depends_on:
            - influxdb
        links:
            - influxdb
        volumes:
            - ./statusok-config:/config-path
        ports:
            - 7321:7321
            
    grafana:
        image: fg2it/grafana-armhf:v4.2.0
        restart: always
        container_name: grafana
        depends_on:
            - influxdb
        links:
            - influxdb
        volumes:
            - ./grafana/etc:/etc/grafana
            - ./grafana/var/lib:/var/lib/grafana
            - ./grafana/var/lib/plugins:/var/lib/grafana/plugins
            - ./grafana/var/log:/var/log/grafana
        ports:
            - 3000:3000
